modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="hzdz_falling2"
version="2.0.0"
displayName="hzdz falling2"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://minecraft.net"
authors="HZDZ"

[[dependencies.hzdz_falling2]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




